version: "3.9"

services:
  build:
    image: mcr.microsoft.com/powershell
    command: pwsh ./Build-Website.ps1
    volumes:
      - .:/app
    working_dir: /app
    user: "1000"
  results-web:
    image: node:16
    command: bash -c "npm install && npm start"
    volumes:
      - ./results:/app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
  web:
    image: nginx
    volumes:
      - ./webcontent:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - build
  web-watch-build:
    build:
      context: .
      dockerfile: Dockerfile.powershell
    command: ./scripts/watch-and-build.sh
    volumes:
      - .:/app
    working_dir: /app
    user: "1000"
