
on:
  push:
    branches: [ master, main ]

jobs:
  build_deploy:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: build website
        shell: pwsh
        run: ./Build-Website

      - name: inject secrets
        run: envsubst '${CONTACT_EMAIL} ${CAPTCHA_PRIVATE_KEY}' < ./webcontent/contact.php.tpl > ./webcontent/contact.php
        env:
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
          CAPTCHA_PRIVATE_KEY: ${{ secrets.CAPTCHA_PRIVATE_KEY }}

      # build react app
      - name: use nodejs 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
      - name: npm install
        run: npm install
        working-directory: results
      - name: npm build
        run: npm run build
        working-directory: results
      - name: copy artifacts to results
        run: mv results/build webcontent/results

      # - name: move webcontent to root because git ftp is silly
      #   run: |
      #     rm -rf results/
      #     mv webcontent/* ./

      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "github@nesvt.org"

      - name: commit
        run: |
          # Stage the file, commit and push
          rm -f .gitignore
          git add -A
          git commit -m "ephemeral commit for git ftp push"
          ls -lah
          pwd
          git config --global --add safe.directory /github/workspace

      # 4.0+ is broken with 1and1    
      # - name: 📂 Sync files
      #   uses: SamKirkland/FTP-Deploy-Action@4.3.3
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.ftp_username }}
      #     password: ${{ secrets.ftp_password }}
      #     server-dir: /dev/
      #     local-dir: ./webcontent/
      #     protocol: ftps-legacy
      #     port: 22

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@3.1.2
        # uses: corymurphy/ftp-deploy-action@3.1.2
        with:
          ftp-server: sftp://${{ secrets.FTP_SERVER }}/
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          git-ftp-args: --insecure
          local-dir: ./webcontent
