
on:
  push:
    branches: [ master, main ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: build website
        shell: pwsh
        run: ./Build-Website
      - name: inject secrets
        run: envsubst '${CONTACT_EMAIL} ${CAPTCHA_PRIVATE_KEY}' < ./webcontent/contact.php.tpl > ./webcontent/contact.php
        env:
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
          CAPTCHA_PRIVATE_KEY: ${{ secrets.CAPTCHA_PRIVATE_KEY }}


      # build react app
      - name: use nodejs 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          check-latest: true
      - name: npm install
        run: npm install
        working-directory: results
      - name: npm build
        run: npm run build
        working-directory: results
      - name: copy artifacts to results
        run: mv results/build webcontent/results

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: ./
          local-dir: ./webcontent/
          # protocol: ftps-legacy
          log-level: verbose
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: ./
          local-dir: ./webcontent/
          log-level: verbose
          # protocol: ftps-legacy
