name: nesvt.vnext cicd pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v4

      # - name: create deployable directory
      #   run: mkdir webcontent

      # - name: inject secrets
      #   run: envsubst '${CONTACT_EMAIL} ${CAPTCHA_PRIVATE_KEY}' < ./site/public/contact.php > ./webcontent/contact.php
      #   env:
      #     CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
      #     CAPTCHA_PRIVATE_KEY: ${{ secrets.CAPTCHA_PRIVATE_KEY }}

      - name: use nodejs 22
        uses: actions/setup-node@v2
        with:
          node-version: '22'
          check-latest: true

      - name: npm install
        run: npm install
        working-directory: site

      - name: npm build
        run: npm run build
        working-directory: site

      # - name: copy build artifacts to webserver
      #   run: mv site/dist/* webcontent/

      - name: copy files to server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -i ~/.ssh/id_rsa -r ./site/dist/* ubuntu@${{ secrets.SSH_SERVER }}:/var/www/oci2.corymurphy.io/html
  
      # ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.SSH_SERVER }} "mkdir -p /app"
      # - name: move webcontent to root because git ftp is silly
      #   run: |
      #     rm -rf site/
      #     rm -rf .github/
      #     rm -rf legacy/
      #     mv webcontent/* ./

